<a href="https://colab.research.google.com/github/fdegolla/MAT-422-Francisco-Degollado/blob/main/MAT422_HW_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT 422 - Homework 1.4

**Name:** Francisco Degollado

## Topics
- 1.4.1 Singular Value Decomposition
- 1.4.2 Low-Rank Matrix Approximations
- 1.4.3 Principal Component Analysis

In [1]:
import numpy as np

## 1.4.1 Singular Value Decomposition

Singular value decomposition (SVD) factors a matrix $A$ into three matrices:

$$
A = U\Sigma V^T
$$

where $U$ and $V$ contain orthonormal vectors and $\Sigma$ contains the singular values.

Consider the matrix:

$$
A =
\begin{bmatrix}
3 & 1\\
1 & 3\\
1 & 1
\end{bmatrix}
$$

We can use Python to compute the SVD and verify that multiplying $U\Sigma V^T$ reconstructs the original matrix $A$.

In [2]:
# Define the matrix A
A = np.array([
    [3.0, 1.0],
    [1.0, 3.0],
    [1.0, 1.0]
])

# Compute the singular value decomposition
U, singular_values, VT = np.linalg.svd(A, full_matrices=False)

print("Matrix U:")
print(U)

print("\nSingular values:")
print(singular_values)

print("\nMatrix V^T:")
print(VT)

Matrix U:
[[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

Singular values:
[4.24264069 2.        ]

Matrix V^T:
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [3]:
# Create the Sigma matrix from the singular values
Sigma = np.diag(singular_values)

# Reconstruct A
reconstructed_A = U @ Sigma @ VT

print("Reconstructed A:")
print(np.round(reconstructed_A, 10))

print("\nSVD reconstructs A:", np.allclose(reconstructed_A, A))

Reconstructed A:
[[3. 1.]
 [1. 3.]
 [1. 1.]]

SVD reconstructs A: True


### Interpretation

The SVD factors the matrix $A$ into $U$, $\Sigma$, and $V^T$. Multiplying these matrices reconstructs the original matrix, and the verification returns `True`. This confirms the decomposition $A = U\Sigma V^T$.

## 1.4.2 Low-Rank Matrix Approximations

A low-rank approximation uses only the largest singular values from the SVD to create a simpler approximation of a matrix.

For the SVD

$$
A = U\Sigma V^T,
$$

a rank-1 approximation keeps only the largest singular value and its corresponding singular vectors:

$$
A_1 = \sigma_1 u_1 v_1^T.
$$

Using the same matrix from the previous section, we can construct a rank-1 approximation and compare it with the original matrix.

In [4]:
# Create a rank-1 approximation of A

# Keep only the first singular value and singular vectors
U1 = U[:, :1]
Sigma1 = np.diag(singular_values[:1])
VT1 = VT[:1, :]

# Construct the rank-1 approximation
A_rank1 = U1 @ Sigma1 @ VT1

print("Original matrix A:")
print(A)

print("\nRank-1 approximation:")
print(np.round(A_rank1, 4))

Original matrix A:
[[3. 1.]
 [1. 3.]
 [1. 1.]]

Rank-1 approximation:
[[2. 2.]
 [2. 2.]
 [1. 1.]]


In [5]:
# Calculate the approximation error
error = np.linalg.norm(A - A_rank1)

print("Approximation error:")
print(error)

print("\nRank of original A:", np.linalg.matrix_rank(A))
print("Rank of approximation:", np.linalg.matrix_rank(A_rank1))

Approximation error:
2.0

Rank of original A: 2
Rank of approximation: 1


### Interpretation

The original matrix has rank 2, while the low-rank approximation has rank 1. By keeping only the largest singular value, we obtain a simpler approximation of the original matrix. The approximation error is $2.0$, showing that some information is lost when the matrix is reduced to rank 1.

## 1.4.3 Principal Component Analysis

Principal component analysis (PCA) is a method used to reduce the dimensionality of data while preserving as much variation as possible.

PCA finds new directions called principal components. The first principal component represents the direction of greatest variation in the data, and the second principal component represents the next greatest variation.

Consider the following two-dimensional data:

$$
X =
\begin{bmatrix}
1 & 2\\
2 & 3\\
3 & 5\\
4 & 4\\
5 & 6
\end{bmatrix}
$$

We can use Python to center the data, calculate the principal components, and determine how much variation is explained by each component.

In [6]:
# Define the data matrix
X = np.array([
    [1.0, 2.0],
    [2.0, 3.0],
    [3.0, 5.0],
    [4.0, 4.0],
    [5.0, 6.0]
])

# Center the data by subtracting the mean
mean = np.mean(X, axis=0)
X_centered = X - mean

print("Original data:")
print(X)

print("\nMean:")
print(mean)

print("\nCentered data:")
print(X_centered)

Original data:
[[1. 2.]
 [2. 3.]
 [3. 5.]
 [4. 4.]
 [5. 6.]]

Mean:
[3. 4.]

Centered data:
[[-2. -2.]
 [-1. -1.]
 [ 0.  1.]
 [ 1.  0.]
 [ 2.  2.]]


In [7]:
# Calculate the covariance matrix
cov_matrix = np.cov(X_centered, rowvar=False)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

# Sort from largest to smallest eigenvalue
indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[indices]
eigenvectors = eigenvectors[:, indices]

# Calculate explained variance ratio
explained_variance = eigenvalues / np.sum(eigenvalues)

print("Covariance matrix:")
print(np.round(cov_matrix, 4))

print("\nEigenvalues:")
print(np.round(eigenvalues, 4))

print("\nPrincipal components:")
print(np.round(eigenvectors, 4))

print("\nExplained variance ratio:")
print(np.round(explained_variance, 4))

Covariance matrix:
[[2.5  2.25]
 [2.25 2.5 ]]

Eigenvalues:
[4.75 0.25]

Principal components:
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

Explained variance ratio:
[0.95 0.05]


In [8]:
# Select the first principal component
PC1 = eigenvectors[:, 0]

# Project the centered data onto PC1
X_pca = X_centered @ PC1

print("First principal component:")
print(np.round(PC1, 4))

print("\nData projected onto PC1:")
print(np.round(X_pca, 4))

First principal component:
[0.7071 0.7071]

Data projected onto PC1:
[-2.8284 -1.4142  0.7071  0.7071  2.8284]


### Interpretation

PCA identifies the directions in the data that contain the most variation. The first principal component explains approximately $95\%$ of the total variance, while the second principal component explains approximately $5\%$. Therefore, most of the information in the original two-dimensional data can be represented using only the first principal component. This demonstrates how PCA can be used for dimensionality reduction.